### ISSUE TITLE
How does bonsai differ from Piston?

### ISSUE THREAD

**Issue by fgadaleta** [Sollimann/bonsai#21]
https://crates.io/crates/piston-ai_behavior

**Comment by Sollimann** [comment]
Bonsai differs from Piston's ai-behavior crate in that it is platform agnostic, where as the ai-behavior crate is tied to the Piston game engine. Bonsai also has additional functionality in that you can generate a digraph from your behavior tree for visualization of your ai logic. Bonsai also supports a Blackboard/database for message passing and data persistence. 

![image](https://github.com/Sollimann/bonsai/assets/25263842/96541122-0247-49da-867d-f08f15ace76b)

I'm also working on a real-time visualization of the behavior tree logic, but I have halted the development for some time now due to other prioritize. I hope to resume the development in not too long:

The PR is a WIP: https://github.com/Sollimann/bonsai/pull/16
