### ISSUE TITLE
Clone breaks BT

### ISSUE THREAD

**Issue by 0awful** [Sollimann/bonsai#31]
Attempting to integrate this project with [GDExt](https://github.com/godot-rust/gdext) I discovered the following behavior.

By simply modifying the `game_tick` function in the Simple NPC Behavior example to have the following:
```
let status = bt.clone().tick()...
```
instead of
```
let status = bt.tick()...
```
I encountered an infinite loop that develops.
```
reached main loop...
NPC is alive...
NPC has action points: 3
Performing action: run. Action points: 2
Performing action: shoot. Action points: 1
NPC has action points: 1
Performing action: run. Action points: 0
Cannot perform action: shoot. Not enough action points.
NPC does not have actions points left... 
Rested for a while... Action points: 1
reached main loop...
NPC is alive...
NPC has action points: 1
Performing action: run. Action points: 0
Cannot perform action: shoot. Not enough action points.
NPC does not have actions points left... 
Rested for a while... Action points: 1
reached main loop...
NPC is alive...
NPC has action points: 1
Performing action: run. Action points: 0
Cannot perform action: shoot. Not enough action points.
NPC does not have actions points left... 
Rested for a while... Action points: 1
reached main loop...
```

[Minimal code example here](https://github.com/0awful/bonsai-minimal-repo). You also need to derive(clone) for your blackboard

My operating assumption was that clone semantics couldn't induce this kind of error, but turns out I don't understand it as well as I thought. Is there a way to resolve this where clone could be used?

(also I see [this is on your kanban board](https://github.com/Sollimann/bonsai/projects/1#card-84030089) when I get my gdext implementation working, would you like a copy?)

**Comment by kaphula** [comment]
If you clone the behavior tree at that point it basically means that the simulation starts all over again infinitely. Notice that the initial behavior tree lives in the main function outside the "game loop" and you are cloning that again and again. 

When this behavior tree is ticked inside the `game_tick`, it stays executing the behavior tree inside the `game_tick` function until the behavior tree reaches the `Rest` action. At this point, `Running` status is returned which means the behavior tree exits the tick function and returns `Running` status. This is how the `RepeatSequence` is programmed to work. If you return `Running` during `RepeatSequence`'s sequence actions, the execution is returned out of the tick function with `Running` status. When you call tick again, the execution returns at the same action where `Running` was previously returned. 

Since you are ticking a cloned version of the behavior tree, these changes get lost once you exit the `game_tick` function leaving the original initial behavior tree unchanged with no tick methods called onto it.

**Comment by 0awful** [comment]
Makes sense. I anticipated clone would clone all internal state in addition to the structure or give a mutable reference to the same data structure. But I understand it working like this. I'll work around this. Thanks for following up.
